FORMAT: 1A
HOST: http://jobs.apiblueprint.org/

# myJobs

API para cadastro de vagas de trabalho.

## Jobs [/jobs]

### List All Jobs [GET]

+ Response 200 (application/json)

        {
            "jobs": [
                { 
                    "id": 1,
                    "title": "Faxineira",
                    "description": "Efetuar limpeza interna e externa do imóvel",
                    "employer": {"id": 1, "name": "Alessandra"},
                    "weekdays": true,
                    "weekends": false,
                    "hoursDay": 6,
                    "wage": 1500,
                    "previousExperience": true,
                    "obs": "Gostar de cães",
                },
                { 
                    "id": 2,
                    "title": "Jardineiro",
                    "description": "Manter os diversos tipos de plantas em ordem nos jardins, eliminar infestações de insetos etc",
                    "employer": {"id": 2, "name": "Rodrigo"},
                    "weekdays": true,
                    "weekends": false,
                    "hoursDay": 4,
                    "wage": 1000,
                    "previousExperience": true,
                    "obs": "Manter as árvores podadas e a grama baixa",
                },
            ]
        }

### Create a New Job [POST]

Create a new job opportunity.

+ Request (application/json)

        { 
            "job": {
                "title": "Mecânico",
                "description": "Efetuar manutenção preventiva e corretiva em automóveis",
                "employer": {"id": 2, "name": "Rodrigo"},
                "weekdays": true,
                "weekends": true,
                "hoursDay": 8,
                "wage": 3000,
                "previousExperience": true,
                "obs": "Experiência com injeção eletrônica e câmbio automático",
            }
        },

+ Response 201 (application/json)

    + Headers

            Location: /jobs/3

    + Body

            { 
                "job": {
                    "id": 3,
                    "title": "Mecânico",
                    "description": "Efetuar manutenção preventiva e corretiva em automóveis",
                    "employer": {"id": 2, "name": "Rodrigo"},
                    "weekdays": true,
                    "weekends": true,
                    "hoursDay": 8,
                    "wage": 3000,
                    "previousExperience": true,
                    "obs": "Experiência com injeção eletrônica e câmbio automático",
                }
            }

## Jobs [/jobs/{id}]

+ Parameters
    + id (number) - ID of the job

### List a Job [GET]

+ Response 200 (application/json)

        {
            jobs: { 
                    "id": 1,
                    "title": "Faxineira",
                    "description": "Efetuar limpeza interna e externa do imóvel",
                    "employer": {"id": 1, "name": "Alessandra"},
                    "weekdays": true,
                    "weekends": false,
                    "hoursDay": 6,
                    "wage": 1500,
                    "previousExperience": true,
                    "obs": "Gostar de cães",
                },
        }

### Update a Job [PUT]

Updates an existing job.

+ Request (application/json)

        { 
            "job": {
                "title": "Mecânico de veículos leves",
                "description": "Efetuar manutenção preventiva e corretiva em automóveis",
                "employer": {"id": 2, "name": "Rodrigo"},
                "weekdays": true,
                "weekends": true,
                "hoursDay": 8,
                "wage": 3000,
                "previousExperience": true,
                "obs": "Experiência com injeção eletrônica e câmbio automático",
            }
        },

+ Response 200 (application/json)

    + Headers

            Location: /jobs/3

    + Body

            { 
                "job": {
                    "id": 3,
                    "title": "Mecânico de veículos leves",
                    "description": "Efetuar manutenção preventiva e corretiva em automóveis",
                    "employer": {"id": 2, "name": "Rodrigo"},
                    "weekdays": true,
                    "weekends": true,
                    "hoursDay": 8,
                    "wage": 3000,
                    "previousExperience": true,
                    "obs": "Experiência com injeção eletrônica e câmbio automático",
                }
            }
            
### Delete a Job [DELETE]

Deletes an existing job.

+ Response 204 (application/json)