FORMAT: 1A
HOST: http://jobs.apiblueprint.org/

# myJobs

API para cadastro de vagas de trabalho.

## Jobs [/jobs]

### List All Jobs [GET]

+ Response 200 (application/json)

        {
            "jobs": [
                { 
                    "id": 1,
                    "title": "Faxineira",
                    "description": "Efetuar limpeza interna e externa do imóvel",
                    "employer": 1,
                    "weekdays": true,
                    "weekends": false,
                    "hoursDay": 6,
                    "wage": 1500,
                    "previousExperience": true,
                    "obs": "Gostar de cães",
                    active: true,
                },
                { 
                    "id": 2,
                    "title": "Jardineiro",
                    "description": "Manter os diversos tipos de plantas em ordem nos jardins, eliminar infestações de insetos etc",
                    "employer": 2,
                    "weekdays": true,
                    "weekends": false,
                    "hoursDay": 4,
                    "wage": 1000,
                    "previousExperience": true,
                    "obs": "Manter as árvores podadas e a grama baixa",
                    active: true,
                },
            ]
        }

## Jobs [/jobs/{id}]

+ Parameters
    + id (number) - ID of the job

### List a Job [GET]

+ Response 200 (application/json)

        {
            jobs: { 
                    "id": 1,
                    "title": "Faxineira",
                    "description": "Efetuar limpeza interna e externa do imóvel",
                    "employer": 1,
                    "weekdays": true,
                    "weekends": false,
                    "hoursDay": 6,
                    "wage": 1500,
                    "previousExperience": true,
                    "obs": "Gostar de cães",
                    active: true,
                },
        }

## Jobs [/job]

### Create a New Job [POST]

+ Request (application/json)

        { 
            "job": {
                "title": "Mecânico",
                "description": "Efetuar manutenção em automóveis",
                "employer": 2,
                "weekdays": true,
                "weekends": true,
                "hoursDay": 8,
                "wage": 3000,
                "previousExperience": true,
                "obs": "",
                active: true,
            }
        },

+ Response 201 (application/json)

    + Headers

            Location: /jobs/3

    + Body

            { 
                "job": {
                    "id": 3,
                    "title": "Mecânico",
                    "description": "Efetuar manutenção em automóveis",
                    "employer": 2,
                    "weekdays": true,
                    "weekends": true,
                    "hoursDay": 8,
                    "wage": 3000,
                    "previousExperience": true,
                    "obs": "",
                    active: true,
                }
            }

## Jobs [/job/{id}]

+ Parameters
    + id (number) - ID of the job
    
### Update a Job [PUT]

+ Request (application/json)

        { 
            "job": {
                "title": "Mecânico de veículos leves",
                "description": "Efetuar manutenção preventiva e corretiva em automóveis",
                "employer": 2,
                "weekdays": true,
                "weekends": true,
                "hoursDay": 8,
                "wage": 3000,
                "previousExperience": true,
                "obs": "Experiência com injeção eletrônica e câmbio automático",
                active: true,
            }
        },

+ Response 200 (application/json)

    + Headers

            Location: /jobs/3

    + Body

            { 
                "job": {
                    "id": 3,
                    "title": "Mecânico de veículos leves",
                    "description": "Efetuar manutenção preventiva e corretiva em automóveis",
                    "employer": 2,
                    "weekdays": true,
                    "weekends": true,
                    "hoursDay": 8,
                    "wage": 3000,
                    "previousExperience": true,
                    "obs": "Experiência com injeção eletrônica e câmbio automático",
                    active: true,
                }
            }
            
### Delete a Job [DELETE]

+ Response 204 (application/json)




## Employers [/employers]

### List All Employers [GET]

+ Response 200 (application/json)

        {
            "employers": [
                { 
                    "id": 1,
                    "name": "Alessandra",
                    active: true,
                },
                { 
                    "id": 2,
                    "name": "Rodrigo",
                    active: true,
                },
            ]
        }

## Employers [/employers/{id}]

+ Parameters
    + id (number) - ID of the employer

### List a Employer [GET]

+ Response 200 (application/json)

        {
            employers: { 
                    "id": 1,
                    "name": "Alessandra",
                    active: true,
                },
        }

## Employers [/employer]

### Create a New Employer [POST]

+ Request (application/json)

        { 
            "employer": {
                "title": "José da Silva",
                active: true,
            }
        },

+ Response 201 (application/json)

    + Headers

            Location: /employers/3

    + Body

            { 
                "employer": {
                    "id": 3,
                    "name": "José da Silva",
                    active: true,
                }
            }

## Employers [/employer/{id}]

+ Parameters
    + id (number) - ID of the employer
    
### Update a Employer [PUT]

+ Request (application/json)

        { 
            "Employer": {
                "name": "José Silva Santos",
                active: true,
            }
        },

+ Response 200 (application/json)

    + Headers

            Location: /employers/3

    + Body

            { 
                "employer": {
                    "id": 3,
                    "name": "José Silva Santos",
                    active: true,
                }
            }
            
### Delete a Employer [DELETE]

+ Response 204 (application/json)